export enum EnumRoles {
  INLOGGEN = 'Algemeen',
  REPARATIE = 'Reparatie',
  BESTELLINGEN = 'Bestellingen',
  KLEDING = 'Kleding',
  PRODUCTIE = 'Productie',
  INMETEN = 'Inmeten',
  FORMULIEREN = 'Formulieren',
  FORMULIEREN_KLANT = 'Formulieren_klant',
  TRACKING = 'Tracking',
  GEPRODUCEERD = 'Geproduceerd',
  BESTELLINGEN_BEHEREN = 'Bestellingen_beheren',
  BINNEN_MELDEN = 'Binnen_melden',
  CONTROLE = 'Controle',
  VOORRAAD = 'Voorraad',
  BERICHTEN_BEHEREN = 'Berichten_beheren',
  AFSPRAKEN = 'Afspraken',
  LOGISTIEK = 'Logistiek',
  RAPPORTAGE = 'Rapportage',
  FINANCIEEL = 'Financieel',
  DECLARATIE = 'Declaratie',
  ROLLEN_BEHEREN = 'Rollen_beheren',
  WIDGETS = 'Widgets',
  ONTWIKKELINGEN_BEHEREN = 'Ontwikkelingen_beheren',
}
